package:
  name: smcpp
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default').lstrip('v') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: ../
  # git_tag: devel

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python {{ python }}
    - git >=2.9.3
    - cython >=0.25
    - setuptools >=33.1
    - numpy >=1.10
    - gmp >=6.1.0
    - gsl >=2.2.1
    - mpfr >=4.0.0
    - setuptools_scm >=1.15
  run:
    - python
    - llvm-openmp  # [osx]
    - cython >=0.25
    - setuptools >=33.1
    - numpy >=1.10
    - gnuplot >=4.6.0
    - gmp >=6.1.0
    - gsl >=2.2.1
    - mpfr >=3.1.5
    - setuptools_scm >=1.15
    - pysam >=0.11
    - matplotlib >=2.0
    - pandas >=0.19
    - python-dateutil >=2.6
    - scikit-learn >=0.19
    - scipy >=0.18
    - six
    - appdirs >=1.4
    - tqdm >=4.10
    - wrapt >=1.10
    - ad >=1.3.2
    - readline >=6.2
    - attrs 
    - msprime >=0.5.0

about:
    home: https://github.com/popgenmethods/smcpp
    license: BSD
    license_file: LICENSE

test:
    imports:
        - smcpp
        - smcpp._smcpp
    source_files:
        - example/example.vcf.gz
        - example/example.vcf.gz.csi
