package:
  name: smcpp
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default').lstrip('v') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: ../
  # git_tag: devel

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools_scm
    - cython
    - git
  host:
    - python
    - numpy
    - gmp
    - gsl
    - mpfr
  run:
    - python
    - numpy 
    - gnuplot
    - gmp
    - gsl
    - mpfr
    - pysam
    - matplotlib
    - pandas
    - scikit-learn
    - scipy
    - appdirs
    - tqdm
    - wrapt 
    - ad
    - msprime

about:
    home: https://github.com/popgenmethods/smcpp
    license: BSD
    license_file: LICENSE

test:
    imports:
        - smcpp
        - smcpp._smcpp
    source_files:
        - example/example.vcf.gz
        - example/example.vcf.gz.csi
