package:
  name: smcpp
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../
  git_rev: v1.15.3

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - numpy >=1.11
  host:
    - python {{ python }}
    - cython
    - numpy >=1.11
    - gmp
    - gsl <=2.5
    - mpfr
    - setuptools_scm
  run:
    - python 
    - {{ pin_compatible('numpy') }}
    - gnuplot
    - gmp
    - gsl <=2.5
    - mpfr
    - pysam >=0.11
    - matplotlib
    - pandas
    - scikit-learn
    - scipy >=1.1.0
    - appdirs
    - tqdm
    - msprime >=0.5
    - seaborn

about:
    home: https://github.com/popgenmethods/smcpp
    license: BSD
    license_file: LICENSE

test:
    imports:
        - smcpp
        - smcpp._smcpp
    source_files:
        - example/example.vcf.gz
        - example/example.vcf.gz.csi
